export const Projects = [
    {
        name: 'BLAME - A Blogging App (Ongoing)',
        github: 'https://github.com/rishabhguptajs/Blogging-App',
        live: 'https://blogwithnoworries.vercel.app',
        desc: 'A Blogging App made with NextJS and TailwindCSS. It has features like authentication, creating, updating and deleting blogs. Also the use of generative AI to generate blog content.',
        tech: ['ReactJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'TailwindCSS', 'Firebase', 'Axios', 'Framer Motion', 'React Router DOM', 'Vite'],
        id: 1,
        type: 'Full-Stack'
    },
    {
        name: 'Oddyssey - E-commerce App (Completed)',
        github: 'https://github.com/rishabhguptajs/Oddyssey---ecommerce-platform',
        live: '',
        desc: 'An E-commerce App made with MERN Stack. It has features like authentication, creating, updating and deleting products, adding to cart and checkout with payments using Stripe.',
        tech: ['ReactJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'TailwindCSS', 'Axios', 'React Router DOM', 'Stripe'],
        type: 'Full-Stack',
    },
    {
        name: "Scalable Backend for E-commerce App",
        github: 'https://github.com/rishabhguptajs/scalable-ecommerce-backend',
        live: "https://scalable-ecommerce-backend-77zq.onrender.com",
        desc: "A scalable backend for an E-commerce App made with NodeJS and ExpressJS. It has features like authentication, RBAC, rate-limiting, and caching using Redis. It has functionalities like CRUD operations for products, users, and orders, mailer, and payment gateway integration.",
        tech: ['NodeJS', 'ExpressJS', 'Typescript', 'MongoDB', 'Redis', 'JWT', 'MailGun', 'Stripe', 'Bcrypt', 'Mongoose', 'Axios', 'Express Rate Limit', 'Docker', 'Dotenv', 'Nodemon'],
        type: "Back-End",
    },
    {
        name: 'Personal Portfolio (Completed)',
        github: 'https://github.com/rishabhguptajs/personal_portfolio',
        live: 'https://rishabhguptajs.vercel.app',
        desc: 'My Personal Portfolio made with NextJS and TailwindCSS. It has features like a blog section, projects section, and a contact form.',
        tech: ['ReactJS', 'NextJS', 'TailwindCSS', 'Axios', 'Framer Motion', 'Vite', 'TypeScript'],
        type: 'Front-End',
    },
    {
        name: 'Saudade - A Youtube Tool (On Hold)',
        github: 'https://github.com/rishabhguptajs/Saudade',
        live: '',
        desc: "A Youtube Tool made with MERN Stack. It's main feature is to increase the productivity and ease of access to the Youtubers for uploading videos, in a remote setting.",
        tech: ['ReactJS', 'Youtube API', 'NodeJS', 'ExpressJS', 'OAuth', 'MongoDB', 'TailwindCSS', 'Axios', 'Cloudinary', 'Framer Motion', 'Vite'],
        type: 'Full-Stack',
    },
    {
        name: 'A To-Do App (Completed)',
        github: 'https://github.com/rishabhguptajs/fullstack_todo',
        live: '',
        desc: 'A To-Do App made using MERN Stack. It uses in-memory storage for storing the tasks and has features like adding, updating and deleting tasks.',
        tech: ['ReactJS', 'NodeJS', 'ExpressJS', 'React Router DOM', 'Axios'],
        type: 'Full-Stack',
    },
    {
        name: 'AI Pantry Tracker',
        github: 'https://github.com/rishabhguptajs/ai-pantry-tracker',
        live: 'https://aipantrytracker.vercel.app/',
        desc: 'AI Pantry Tracker helps you manage your pantry and discover new recipes effortlessly. Add, update, and track items with ease. Our AI suggests recipes based on your ingredients, reducing food waste and saving time. Enjoy advanced features like image classification for efficient inventory management. Perfect for home cooks and busy professionals.',
        tech: ['NextJS', 'TailwindCSS', 'Firebase', 'TypeScript'],
        type: 'Front-End',
    },
    {
        name: 'AI Image Generator (Completed)',
        github: 'https://github.com/rishabhguptajs/imageGen',
        live: '',
        desc: 'An AI Image Generator made using ReactJS and OpenAI. It uses OpenAI API to generate images based on the user input.',
        tech: ['ReactJS', 'OpenAI', 'Axios'],
        type: 'Front-End',
    },
    {
        name: 'SplitMe - A Bill Splitting App (Completed)',
        github: 'https://github.com/rishabhguptajs/fintech-app',
        live: 'https://splitme.vercel.app/',
        desc: 'A landing page for a Bill Splitting App made using ReactJS and raw CSS. It has features like adding, updating and deleting bills.',
        tech: ['ReactJS', 'TailwindCSS', 'JavaScript', 'HTML', 'CSS'],
        type: 'Front-End',
    }
]
